### ISSUE TITLE
increment by 8

### ISSUE THREAD

**Issue by gabriele-carbonai** [modernkernel/yii2-photoswipe#2]
Hello I have this problem with the gallery, it is alway increment 8 more photo.
example:
I open gallery with 10 photo ( 1/10 ) and when i click next the photos are 18 ( 2/18 ).
after the 10 photos, is continue with black background ( 11/18, 12/18 etc... )
I try to put example code but have the same problem.
thanks.
Gabriele

**Comment by harrytang** [comment]
Hello,

Can you please show me your code ?

**Comment by gabriele-carbonai** [comment]
Of course, is pretty easy code.
```php
<?php 
$items = array();

foreach( $images = Images::find()->where('projects_id = ' . $model->project_id)->orderBy([
      'sort'=>SORT_ASC,
      'projects_images_id' => SORT_DESC,
   ])->limit(100)->offset($offset)->all() as $img): 

   $items[] =  [
      "image" => Yii::$app->request->baseUrl ."/img/projects/1024/". $img->image,
      'size' => "1024x768",
      'imgClass' => 'hover',
      'thumb' =>  Yii::$app->request->baseUrl ."/img/projects/600/". $img->image,
   ];

endforeach;
                     
echo \modernkernel\photoswipe\Gallery::widget([
    'items' => $items
])
?>
```
note that i try to replace the print part with your static example code

here you can see a gif [https://gyazo.com/b557d4bd05ad3a06cecd7a0ded2a6b65](https://gyazo.com/b557d4bd05ad3a06cecd7a0ded2a6b65)

thank you

**Comment by gabriele-carbonai** [comment]
I chenged in gallery.php this code
```javascript 
var pswpElement =document.querySelectorAll('.pswp')[0]
```
to this
```javascript 
 var pswpElement = $('.pswp' ); 
```
now I have 18 photos from begin instead of 10, but anymore black background and is always starting from one photo that is not the first one or is not the selected photo

**Comment by harrytang** [comment]
Thanks,

The example code works fine, even with more images.

Can you please paste your `var_dump($items)` here.

**Comment by gabriele-carbonai** [comment]
I think I found the problem and is from other script.
thanks for your availability
